print('backslash: \\')
print('single-quote: \'')
print("double-quote: \"")
print('ascii bell: \a')
print('backspace: ab\bcdef')
print('ascii formfeed: \f')
print('ascii linefeed: \n')
print('character named "DAGGER" in the unicode database: \N{DAGGER}')
print('carriage return: \r')
print('horizontal tab" \t*')
print('character with 16-bit hex value 1234: \u1234')
print('character with 32-bit hex value 0000035c: \U0000035c')
print('ascii vertical tab: \v')
print('character with octal value 000: \000')
print('character with hex value ff: \xff')
